# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# The public documentation URL, used for sitemap.xml
headerbaseurl: //www.nativescript.org
destination: ./sidekick

navigation:
## List your directory names and order here, like this:
    intro:
        position: 10
        title: Introduction
    getting-started:
        position: 20
        title: Get Started
    user-guide:
        position: 30
        title: User Guide
    user-guide/logging-in:
        position: 33
        title: Logging in Sidekick
    user-guide/sidekick-settings:
        position: 35
        title: Sidekick Settings
    user-guide/create-app:
        position: 40
        title: Creating Your App 
    user-guide/configure-app:
        position: 45
        title: Configuring Your App    
    user-guide/add-page:
        position: 50
        title: Adding a New Page to Your App         
    user-guide/code-signing:
        position: 55
        title: Code Signing Your App
    user-guide/code-signing/code-signing-for-ios:
        position: 60
        title: Code Signing for iOS Apps
    user-guide/build-app:
        position: 65
        title: Building Your App
    user-guide/run-app:
        position: 70
        title: Running Your App on a Device
    user-guide/publish-app:
        position: 75
        title: Publishing Your App
    user-guide/enterprise-auth:
        position: 80
        title: Enterprise Auth

## The application virtual path
baseurl: /sidekick
   
## The highlighting in the header   
skselected: "selected"

## The product name
productName: "NativeScript Sidekick"
    
## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "page"
        category: "default"

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
"ns": "NativeScript"
"sk": "Sidekick"
"ns-sk": "NativeScript Sidekick"
"ns-cli": "NativeScript CLI"
        
# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

# The google services configuration
google_tag_manager: GTM-W58JDD
google_custom_search: '001595215763381649090:asl7kpbijam'    
    
## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
# Feedback Form Google Sheet ID
ff-sheet-id: 1Njk-CD9m_mKw_jSRBV2p6quwEOAKRZnUPJgeUrA1ZFA
